[package]
name = "dexlyn-perp-trade"
version = "1.0.0"
authors = []

[addresses]
#QA Address
dexlyn = "0x3191f19158cc850fea33ba5e98f82bdd33988b4aeeb3e3863d639e6f24638044"


[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dev-dependencies]
