[package]
name = "UniveralRouter"
version = "1.0.0"
authors = []

[addresses]
dexlyn_aggregator = "0xda93ad85d8098b81b2a314792792c50be6e4931267ff5fefa433cb75195a299d"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"
